(deffacts Datos
    (FichaPaciente (Nombre Carlos) (Edad 1) (Casado No) (Sexo Masculino) (Peso 10))
    (FichaPaciente (Nombre Alicia) (Edad 27) (Casado Si) (Sexo Femenino) (Peso 65))
    (FichaPaciente (Nombre Clara) (Edad 1) (Casado No) (Sexo Femenino) (Peso 11))
    (FichaPaciente (Nombre Manuel) (Edad 28) (Casado Si) (Sexo Masculino) (Peso 79))
    (DatosExploracion (Nombre Carlos) (Sintomas picor rojo vesiculas inflamada) (GravedadAfeccion Grave))
    (DatosExploracion (Nombre Alicia) (Sintomas picor rojo) (GravedadAfeccion Normal))
    (DatosExploracion (Nombre Clara) (Sintomas picor rojo vesiculas inflamada) (GravedadAfeccion Normal))
    (DatosExploracion (Nombre Manuel) (Sintomas vesiculas normal) (GravedadAfeccion Normal))
)